Repository hashicorp/packer, pull requests merged in 2019-06, with the labels that each got.

#7707 Enable encrypted AMI sharing across accounts
  builder/amazon/common/ami_config.go
  builder/amazon/common/ami_config_test.go
Labels: builder/amazon, enhancement

#7526 Add tags to instance in CloudStack builder
  builder/cloudstack/config.go
  builder/cloudstack/step_create_instance.go
Labels: waiting-reply

#7720 Add feature to import user-data from a file
  builder/googlecompute/config.go
  builder/googlecompute/config_test.go
  builder/googlecompute/step_create_instance.go
  builder/googlecompute/step_create_instance_test.go
Labels: builder/google, enhancement

#7737 retry.Backoff: document
  builder/amazon/common/step_create_tags.go
  common/retry/retry.go
Labels: core, docs

#7800 Smb getter
  common/step_download.go
Labels: regression, windows-host

#7774 Make salt-masterless provisioner respect disable_sudo directive for all commands
  provisioner/salt-masterless/provisioner.go
Labels: community-supported plugin, provisioner/salt

#7804 parse checksum file so that we can use the checksums inside in the vm…
  common/iso_config.go
  common/iso_config_test.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-getter/README.md
  vendor/github.com/hashicorp/go-getter/checksum.go
  vendor/github.com/hashicorp/go-getter/decompress_zip.go
  vendor/github.com/hashicorp/go-getter/detect_bitbucket.go
  vendor/github.com/hashicorp/go-getter/get_git.go
  vendor/modules.txt
Labels: builder/vmware-esxi, regression
