Repository hashicorp/packer, pull requests merged in 2022-12, with the labels that each got.

#12139 chore: Update Digital Team Files
  website/Makefile
Labels: website, backport/website

#12131 Add Nutanix plugin docs
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12152 command/validate: Add `-evaluate-datasources` flag to command help text
  command/validate.go
Labels: enhancement

#12126 website: Added Tart builder
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12158 go.mod: bump golang.org/net to 0.4.0
  go.mod
  go.sum
Labels: tech-debt

#12166 Update Go checks to run on pull_requests
  .github/workflows/go-test.yml
  .github/workflows/go-validate.yml
Labels: tech-debt

#12167 Update BuildBlock with valid HCL2Ref
  command/validate_test.go
  hcl2template/types.build.go
Labels: bug

#12161 Bump github.com/hashicorp/go-getter/v2
  go.mod
  go.sum
Labels: tech-debt
