Repository hashicorp/packer, pull requests merged in 2022-08, with the labels that each got.

#11917 Bump bundled plugins to latest available version
  go.mod
  go.sum
  scripts/upgrade_plugins.sh
Labels: tech-debt

#11882 Introduces the post publish website event
  .release/ci.hcl
Labels: backport/1.8.x

#11928 Update comments used by generated docs
  datasource/hcp-packer-image/data.go
  datasource/hcp-packer-iteration/data.go
  datasource/packer-image-iteration/data.go
Labels: docs

#11934 Update CHANGELOG
  CHANGELOG.md
Labels: docs

#11937 Add github.com/vmware-samples to list of template repositories
  website/content/community-tools.mdx
Labels: docs, backport/website

#11951 Adds packer plugin for Mondoo
  website/data/plugins-manifest.json
Labels: docs, backport/website
