Repository hashicorp/packer, pull requests merged in 2022-06, with the labels that each got.

#11833 Update engine.mdx
  website/content/docs/templates/legacy_json_templates/engine.mdx
Labels: docs, backport/website

#11832 Associate Packer build to HCP Packer parent iteration
  hcl2template/common_test.go
  hcl2template/types.build.go
  hcl2template/types.build.hcp_packer_registry.go
  hcl2template/types.build.hcp_packer_registry_test.go
  internal/registry/service.go
  internal/registry/types.bucket.go
  internal/registry/types.bucket_service_test.go
  internal/registry/types.bucket_test.go
Labels: enhancement

#11843 Bump packer-plugin-sdk to latest version v0.3.0
  go.mod
  go.sum
Labels: dependencies
