Repository hashicorp/packer, pull requests merged in 2022-05, with the labels that each got.

#11743 Make Builders Overview Page Clearer
  website/content/docs/builders/index.mdx
Labels: docs, backport/website, backport/1.8.x

#11749 Added mention of HCL in Terminology>Templates
  website/content/docs/terminology.mdx
Labels: docs, backport/website, backport/1.7.x, backport/1.8.x

#11765 Update builders index page
  website/content/docs/builders/index.mdx
Labels: docs, backport/website, backport/1.7.x

#11771 fix: work around deleted plugin release
  website/data/plugins-manifest.json
Labels: docs, backport/website

#11791 Makefile: use go install for install-gen-deps
  Makefile
Labels: build, tech-debt

#11797 docs: Update for packer config file location docs
  website/content/docs/configure.mdx
Labels: docs, backport/website

#11803 Update CHANGELOG
  CHANGELOG.md
Labels: docs

#11805 Update project GitHub actions
  .github/workflows/issues-opened.yml
  .github/workflows/pull-requests-opened.yml
Labels: tech-debt

#11806 Migrate to internal Registry tests
  .github/workflows/acceptance-test.yml
  internal/registry/acctest/par.go
  internal/registry/acctest/par_test.go
  internal/registry/acctest/test-fixtures/build.pkr.hcl
  internal/registry/acctest/test-fixtures/ds.pkr.hcl
Labels: github_actions

#11810 Try curl for getting HCP Access Token in HPATS
  .github/workflows/acceptance-test.yml
Labels: tech-debt

#11822 Put in dev mode 1.8.2
  CHANGELOG.md
  version/version.go
Labels: tech-debt

#11798 Improve clarity
  provisioner/file/provisioner.go
  website/content/partials/provisioner/file/Config-required.mdx
Labels: docs

#11825 Add workflow to link to discuss on new question
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/auto-close-stale-issues.yml
  .github/workflows/issues-opened.yml
Labels: docs, tech-debt
