Repository hashicorp/packer, pull requests merged in 2023-03, with the labels that each got.

#12290 Update JSON template does not return substitute values in 1.8.6 version
  packer/core.go
  packer/core_test.go
  packer/test-fixtures/build-interpolated-name.json
Labels: bug, regression, backport/1.8.x

#12291 website: Update plugin tier for Nutanix to partner verified
  website/data/plugins-manifest.json
Labels: docs, backport/1.8.x

#12294 Update golang.org/x/net to address GO-2023-1571
  go.mod
  go.sum
Labels: security

#12150 Add external plugin docs
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12202 Register documentation for Volcengine plugin
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12317 website: adds content-check command and README update
  website/README.md
  website/package-lock.json
  website/package.json
Labels: website, docs

#12329 Migrate external Linode plugin to linode/packer-plugin-linode
  command/vendored_plugins.go
  go.mod
  go.sum
  website/data/plugins-manifest.json
Labels: backport/1.8.x
