Repository hashicorp/packer, pull requests merged in 2023-05, with the labels that each got.

#12391 [HPR-1038] Remove circular reference between data source doc pages
  website/content/docs/templates/hcl_templates/datasources.mdx
Labels: docs, backport/website

#12400 Fixed formatting issue
  website/content/docs/templates/hcl_templates/blocks/build/post-processors.mdx
Labels: docs

#12402 .go-version: Bump version of Go to 1.20.4
  .go-version
Labels: tech-debt, backport/1.8.x

#12401 Update CHANGELOG
  CHANGELOG.md
Labels: tech-debt, backport/1.8.x

#12408 Update ldflags used to build release binaries
  .github/workflows/build.yml
Labels: crt, backport/1.8.x

#12418 Align Packer logo color
  website/public/img/logo-hashicorp.svg
  website/public/img/logo-packer-padded.svg
  website/public/img/logo-text.svg
Labels: docs

#12437 Bump github.com/shirou/gopsutil to v3
  background_check.go
  go.mod
  go.sum
Labels: backport/1.8.x

#12446 Remove invalid quote from ldflags
  .github/workflows/build.yml
Labels: tech-debt
