Repository hashicorp/packer, pull requests merged in 2023-07, with the labels that each got.

#12476 [HPR-1189] Migrate external Parallels plugin to Parallels/packer-plugin-parallels
  command/vendored_plugins.go
  go.mod
  go.sum
  website/data/plugins-manifest.json
Labels: backport/website, backport/1.9.x

#12485 [HPR-941] Update plugin loading documentation
  website/content/docs/configure.mdx
  website/content/docs/plugins/install-plugins.mdx
  website/content/partials/plugins/plugin-location.mdx
Labels: docs, backport/website, backport/1.9.x

#12505 Makefile: remove mode-check target
  Makefile
Labels: tech-debt

#12508 Fix minor typo
  website/content/docs/templates/hcl_templates/functions/contextual/vault.mdx
Labels: docs, backport/website

#12517 CHANGELOG: add changelog for Packer 1.9.2
  CHANGELOG.md
Labels: backport/1.9.x

#12522 CHANGELOG: prepare for 1.9.3
  CHANGELOG.md
Labels: backport/1.9.x

#12493 docs: fix typo
  website/content/docs/templates/hcl_templates/functions/collection/lookup.mdx
Labels: docs, backport/website

#12530 [HPR-1248] .github/workflows: Replace untrusted GHA in repo workflows
  .github/workflows/issues-opened.yml
  .github/workflows/jira.yml
Labels: tech-debt

#12449 issue-comment-created: Add guard for labels
  .github/workflows/issue-comment-created.yml
Labels: tech-debt

#12534 .github: fix issues-opened.yml workflow
  .github/workflows/issues-opened.yml
Labels: tech-debt

#12536 packer: track bundled plugins usage on telemetry
  command/meta.go
  packer/telemetry.go
Labels: core, backport/1.9.x
