Repository hashicorp/packer, pull requests merged in 2023-02, with the labels that each got.

#12245 Add release branches to CRT build pipeline
  .github/workflows/build.yml
  .release/ci.hcl
Labels: tech-debt, backport/1.8.x

#12248 add changelog update for vendor label for linux packaging
  CHANGELOG.md
Labels: docs, backport/1.8.x

#12251 Bump development version to 1.9.0
  version/VERSION
  version/version.go
Labels: tech-debt

#12250 cmd/hcl2_upgrade: Fix crash when variables block is undefined
  command/hcl2_upgrade.go
  command/hcl2_upgrade_test.go
  command/test-fixtures/hcl2_upgrade/varfile-with-no-variables-block/expected.pkr.hcl
  command/test-fixtures/hcl2_upgrade/varfile-with-no-variables-block/input.json
  command/test-fixtures/hcl2_upgrade/varfile-with-no-variables-block/variables.json
Labels: bug, regression, backport/1.8.x

#12249 Update instance runner for workflow
  .github/workflows/create-release-branch.yml
Labels: tech-debt

#12270 Update github.com/hashicorp/go-getter/v2 pkgs to address CVE-2023-0475
  go.mod
  go.sum
Labels: backport/1.8.x
