Repository hashicorp/packer, pull requests merged in 2023-08, with the labels that each got.

#12544 core: Fix custom plugin loading in current working directory
  packer/plugin.go
  packer/plugin_discover_test.go
Labels: bug, regression, backport/1.9.x

#12549 Add build tags to skip amd64 tests on darwin/arm64
  command/init_test.go
  command/plugins_install_test.go
  command/plugins_remove_test.go
Labels: tech-debt, backport/1.9.x

#12552 Removed repetitive statement from HCP debug logs
  hcl2template/types.packer_config.go
Labels: tech-debt, backport/1.9.x

#12561 go.mod: bump golang.org/x/net to v0.13.0
  go.mod
  go.sum
Labels: security, backport/1.9.x

#12570 Update product licensing to BUSL-1.1
  .copywrite.hcl
  .github/workflows/build.yml
Labels: crt, backport/1.9.x

#12571 Update terminology to reflect community editions of Packer
  website/content/docs/commands/init.mdx
  website/content/docs/index.mdx
  website/content/docs/intro/index.mdx
  website/content/docs/partnerships.mdx
  website/content/guides/packer-on-cicd/trigger-tfe.mdx
Labels: docs, backport/1.9.x

#12576 Document PLSP-related environment variables
  website/content/docs/hcp/index.mdx
Labels: docs, backport/website, backport/1.9.x

#12587 Rename duplicate ami name to fix failing test
  acctest/plugin/test-fixtures/basic_amazon_with_required_plugins.pkr.hcl
Labels: tech-debt

#12589 Prepare for 1.9.4 dev mode
  CHANGELOG.md
Labels: tech-debt, backport/1.9.x

#12566 packer: remove implicit required plugins
  command/init.go
  command/plugins_install.go
  command/plugins_installed.go
  command/plugins_remove.go
  hcl2template/parser.go
  hcl2template/plugin.go
  hcl2template/types.required_plugins.go
  hcl2template/types.required_plugins_test.go
  main.go
  packer/plugin-getter/plugins.go
  packer/plugin.go
  website/content/docs/commands/init.mdx
Labels: tech-debt, backport/1.9.x

#12592 telemetry: Add nil check in SetBundledUsage
  packer/telemetry.go
  packer/telemetry_test.go
Labels: bug, core, regression, backport/1.9.x

#12595 CHANGELOG: cut 1.9.4 release
  CHANGELOG.md
Labels: backport/1.9.x

#12598 .go-version: bump version of Go to 1.20.7
  .go-version
Labels: backport/1.9.x

#12601 Changelog setup 1.9.5
  CHANGELOG.md
Labels: backport/1.9.x

#12604 Bump backport assistant to latest version
  .github/workflows/backport.yml
Labels: tech-debt, github_actions

#12609 Updating Community Tools webpage
  website/content/docs/community-tools.mdx
Labels: docs, backport/website

#12593 Set ivoronin/packer-plugin-sshkey version to 'latest'
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12569 Update version output for `-v` and `--version` flags
  main.go
Labels: enhancement
