Repository hashicorp/packer, pull requests merged in 2023-12, with the labels that each got.

#12736 Remove migrated plugins from old plugin docs framework
  website/data/plugins-manifest.json
Labels: docs, backport/website

#12731 plugin-getter: don't rely only on version for list
  packer/plugin-getter/plugins.go
  packer/plugin-getter/plugins_test.go
  packer/plugin-getter/testdata/plugins_3/github.com/hashicorp/alazon/packer-plugin-alazon_v1.2.5_x5.0_linux_amd64
  packer/plugin-getter/testdata/plugins_3/github.com/hashicorp/alazon/packer-plugin-alazon_v1.2.5_x5.0_linux_amd64_SHA256SUM
  packer/plugin-getter/testdata/plugins_3/github.com/hashicorp/amazon/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64
  packer/plugin-getter/testdata/plugins_3/github.com/hashicorp/amazon/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64_SHA256SUM
Labels: backport/1.10.x

#12739 Update CHANGELOG for 1.10.0 release
  CHANGELOG.md
Labels: docs, backport/1.10.x
