Repository hashicorp/packer, pull requests merged in 2023-11, with the labels that each got.

#12678 docs: fix aws_secretsmanager Title Name
  website/content/docs/templates/hcl_templates/functions/contextual/aws_secretsmanager.mdx
Labels: docs, backport/website

#12689 scripts/prepare_changelog: Replace python for with gh and jq commands
  scripts/prepare_changelog.sh
Labels: tech-debt, backport/1.9.x

#12690 Bump Go to 1.20.11 to mitigate against insecure Windows path parsing
  .go-version
Labels: security, backport/1.9.x

#12694 Remove dangling upgrade external plugins script
  scripts/upgrade_plugins.sh
Labels: backport/1.10.x

#12698 deps: Bump github.com/hashicorp/hcp-sdk-go to v0.73.0
  go.mod
  go.sum
  internal/hcp/api/client.go
  internal/hcp/api/client_test.go
  internal/hcp/api/mock_service.go
Labels: dependencies, backport/1.10.x

#12705 packer: link to docs if a component is missing
  hcl2template/plugin.go
  packer/core.go
Labels: enhancement, backport/1.10.x

#12712 hcl2: don't show an empty source on var errors
  hcl2template/types.variables.go
Labels: hcl2, backport/1.10.x

#12720 cmd/hcl2upgrade: Add VirtualBox as known plugin
  command/hcl2_upgrade.go
Labels: backport/1.10.x

#12723 Bump github.com/go-jose/go-jose/v3 to address GO-2023-2334
  go.mod
  go.sum
Labels: dependencies
