Repository hashicorp/packer, pull requests merged in 2023-06, with the labels that each got.

#12452 [HPR-1184] hcp: support HCP_PROJECT_ID environment variable
  internal/hcp/api/client.go
  internal/hcp/api/client_test.go
  internal/hcp/env/env.go
  internal/hcp/env/variables.go
  website/content/docs/hcp/index.mdx
Labels: bug, backport/1.9.x

#12457 CHANGELOG: fix latest release version
  CHANGELOG.md
Labels: docs, backport/1.9.x

#12459 CHANGELOG: prepare for upcoming v1.9.2
  CHANGELOG.md
Labels: docs, backport/1.9.x

#12464 docs: add a paragraph on fingerprint generation
  website/content/docs/hcp/index.mdx
Labels: backport/website

#12478 docs: move community tools to docs folder
  website/content/docs/community-tools.mdx
  website/data/docs-nav-data.json
Labels: docs, backport/website
