Repository hashicorp/packer, pull requests merged in 2024-02, with the labels that each got.

#12836 Remove reference to old External plugins nav
  .github/workflows/check-plugin-docs.js
  .github/workflows/check-plugin-docs.yml
  website/content/docs/plugins/install-plugins.mdx
  website/data/docs-nav-data.json
Labels: docs, backport/website

#12835 build: don't suggest lack of HCP support on fail
  command/build.go
  internal/hcp/registry/types.bucket.go
Labels: enhancement

#12843 Update Terminology Docs With New HCP Packer Nomenclature
  website/content/docs/terminology.mdx
Labels: docs, backport/website

#12855 command: add dev support for plugins install
  command/plugins_install.go
Labels: enhancement

#12854 hcp: fix hcp artifact extraction method
  internal/hcp/registry/types.bucket.go
  internal/hcp/registry/types.bucket_test.go
Labels: bug, backport/1.10.x
