Repository hashicorp/packer, pull requests merged in 2024-05, with the labels that each got.

#12936 Add thread-safe add and get methods for plugin storage
  packer/build.go
  packer/plugin.go
Labels: bug

#12956 Bump actions/checkout to address Node.js 16 deprecation issues
  .github/workflows/acceptance-test.yml
  .github/workflows/build.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/go-test.yml
  .github/workflows/go-validate.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issues-opened.yml
  .github/workflows/nightly-release.yml
Labels: dependencies, security

#12957 Bump actions/setup-go to address Node.js 16 deprecation issues
  .github/workflows/acceptance-test.yml
  .github/workflows/go-test.yml
  .github/workflows/go-validate.yml
Labels: dependencies, security

#12958 Bump required actions to address Node.js 16 deprecation issue
  .github/workflows/acceptance-test.yml
  .github/workflows/auto-close-stale-issues.yml
  .github/workflows/build.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/go-test.yml
  .github/workflows/go-validate.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issues-opened.yml
  .github/workflows/jira.yml
  .github/workflows/lock.yml
  .github/workflows/nightly-release.yml
Labels: dependencies, security

#12959 Update internal HashiCorp actions to address Node 20 deprecation
  .github/workflows/build.yml
Labels: dependencies, security

#12964 docs: fix typo in HCP Packer artifact/version docs
  website/content/docs/datasources/hcp/hcp-packer-artifact.mdx
  website/content/docs/datasources/hcp/hcp-packer-version.mdx
Labels: docs, backport/website

#12967 packer: error multiple paths in PACKER_PLUGIN_PATH
  packer/plugin_folders.go
Labels: enhancement

#12972 packer: register plugin components only once
  hcl2template/plugin.go
  packer/plugin.go
Labels: enhancement

#12969 [HPR-1754] Update Packer Plugins remove command page
  command/plugins_remove.go
  website/content/docs/commands/plugins/remove.mdx
Labels: docs

#12974 docs: update plugins install command documentation
  website/content/docs/commands/plugins/install.mdx
Labels: docs

#12894 Update Example of Parsing a Manifest to Use Only `jq`
  website/content/docs/post-processors/manifest.mdx
Labels: docs, backport/website

#12978 addrs: require at least 3 parts to source URIs
  hcl2template/addrs/plugin.go
  hcl2template/addrs/plugin_test.go
  hcl2template/types.packer_config_test.go
Labels: tech-debt

#12946 Update CHANGELOG for Packer 1.11.0-beta
  CHANGELOG.md
Labels: docs

#12980 packer: don't load plugins with metadata in name
  packer/plugin-getter/plugins.go
Labels: bug

#12984 Bump Go version to 1.12.10 to address CVE-2024-24787
  .go-version
Labels: security

#12986 website: fix myawesomecloud reference
  website/content/docs/plugins/install-plugins.mdx
Labels: docs

#12989 datasource/http: don't error on 2xx code
  datasource/http/data.go
Labels: bug

#12997 hcl2template: add text(encode|decode)base64 funcs
  hcl2template/functions.go
  website/content/docs/templates/hcl_templates/functions/encoding/textdecodebase64.mdx
  website/content/docs/templates/hcl_templates/functions/encoding/textencodebase64.mdx
  website/data/docs-nav-data.json
Labels: enhancement

#12999 commands: reject constraints with pre-releases
  command/plugins_install.go
  hcl2template/types.required_plugins.go
Labels: tech-debt

#13002 scripts: re-add wait for changelog listing
  scripts/prepare_changelog.sh
Labels: tech-debt, backport/1.11.x

#13008 docs: consistent code blocks around types
  website/content/docs/plugins/creation/custom-builders.mdx
Labels: docs, backport/website, backport/1.11.x

#12995 Update plugins install docs for v1.11.0
  website/content/docs/commands/init.mdx
  website/content/docs/commands/plugins/install.mdx
  website/content/docs/community-tools.mdx
  website/content/docs/configure.mdx
  website/content/docs/plugins/creation/custom-builders.mdx
  website/content/docs/plugins/creation/index.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/install-plugins.mdx
  website/content/docs/plugins/install.mdx
  website/content/docs/release-notes/v1_11.mdx
  website/content/docs/templates/hcl_templates/blocks/packer.mdx
  website/content/docs/upgrade/v1_11.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, backport/1.11.x

#13013 version: bump main to 1.12.0-dev
  version/VERSION
Labels: tech-debt

#13014 version: bump version to point to 1.11.1-dev
  version/VERSION
Labels: tech-debt
