Repository hashicorp/packer, pull requests merged in 2024-08, with the labels that each got.

#13132 Add artifacts manifest (automatically generated)
  .release/packer-artifacts.hcl
Labels: crt, backport/1.11.x

#13135 docs: update manually installing plugins docs
  website/content/docs/plugins/install.mdx
Labels: docs

#13119 Enable github workflows on feature branches
  .github/workflows/build.yml
  .github/workflows/go-test.yml
  .github/workflows/go-validate.yml
Labels: tech-debt

#13142 [Feature] Add base64gzip function support to Packer template
  hcl2template/function/encoding.go
  hcl2template/function/encoding_test.go
  hcl2template/functions.go
  website/content/docs/templates/hcl_templates/functions/encoding/base64gzip.mdx
  website/data/docs-nav-data.json
Labels: enhancement
