Repository hashicorp/packer, pull requests merged in 2024-04, with the labels that each got.

#12910 Backport Build Metadata Phase 1 Release
  go.mod
  go.sum
  hcl2template/types.build.hcp_packer_registry_test.go
  hcl2template/types.build_test.go
  hcl2template/types.datasource_test.go
  hcl2template/types.packer_config.go
  hcl2template/types.packer_config_test.go
  hcl2template/types.source_test.go
  hcl2template/types.variables_test.go
  internal/hcp/api/service_build.go
  internal/hcp/registry/hcl.go
  internal/hcp/registry/json.go
  internal/hcp/registry/types.bucket.go
  internal/hcp/registry/types.builds.go
  internal/hcp/registry/types.version.go
  packer/build.go
  packer/plugin.go
Labels: core, hcp

#12923 Report metadata only when the build completes
  internal/hcp/registry/hcl.go
  internal/hcp/registry/json.go
  internal/hcp/registry/types.bucket.go
Labels: core, hcp

#12924 Bump golang.org/x/net to v0.24.0 to address GO-2024-2687
  go.mod
  go.sum
Labels: security, backport/1.10.x

#12928 Bump github.com/go-jose/go-jose/v3 to address GHSA-c5q2-7r4c-mv6g
  go.mod
  go.sum
Labels: security

#12938 Add CHANGELOG entries for 1.10.3
  CHANGELOG.md
Labels: docs

#12940 Dockerfile: Add Product directory to /usr/share/doc directory
  Dockerfile
Labels: bug, crt

#12933 version: compute SemVer from rawVersion
  version/version.go
Labels: bug, tech-debt

#12944 Add missing option doc for 'packer fmt'
  website/content/docs/commands/fmt.mdx
Labels: docs, backport/1.10.x

#12911 packer: relax constraints on local sources
  acctest/plugin/component_acc_test.go
  acctest/plugin/plugin_acc_test.go
  command/plugins_install.go
  hcl2template/addrs/plugin.go
  hcl2template/addrs/plugin_test.go
  hcl2template/types.packer_config_test.go
  hcl2template/types.required_plugins_test.go
  packer/plugin-getter/github/getter.go
  packer/plugin-getter/plugins.go
  packer/plugin-getter/plugins_test.go
Labels: enhancement, plugin-block, command/plugins
