Repository hashicorp/packer, pull requests merged in 2024-09, with the labels that each got.

#13160 Bump Go 1.22.7
  .go-version
Labels: tech-debt, backport/1.11.x

#13163 packer_test: make PluginTestDir a structure
  packer_test/common/commands.go
  packer_test/common/plugin.go
  packer_test/core_tests/local_eval_test.go
  packer_test/plugin_tests/init_test.go
  packer_test/plugin_tests/install_test.go
  packer_test/plugin_tests/loading_test.go
  packer_test/plugin_tests/plugins_remove_test.go
Labels: tech-debt

#13165 hcp: don't continue if HEAD doesn't exist
  internal/hcp/registry/metadata/vcs.go
Labels: bug
