Repository hashicorp/packer, pull requests merged in 2024-03, with the labels that each got.

#12860 Packer tracks Version and Plugins Metadata
  hcl2template/types.build.hcp_packer_registry_test.go
  hcl2template/types.build_test.go
  hcl2template/types.datasource_test.go
  hcl2template/types.packer_config.go
  hcl2template/types.packer_config_test.go
  hcl2template/types.source_test.go
  hcl2template/types.variables_test.go
  internal/hcp/registry/hcl.go
  internal/hcp/registry/json.go
  packer/build.go
  packer/plugin.go
Labels: core, hcp

#12867 Bump google.golang.org/protobuf to address CVE-2024-24786
  go.mod
  go.sum
Labels: backport/1.10.x

#12869 Bump Go to 1.21.8
  .go-version
  go.mod
  go.sum
Labels: tech-debt

#12870 fmt: print parse errors on error
  command/fmt_test.go
  command/test-fixtures/fmt_errs/malformed.pkr.hcl
  hcl2template/formatter.go
Labels: enhancement, backport/1.10.x

#12874 Fix invalid path for copy command
  website/content/docs/plugins/creation/index.mdx
Labels: website, docs, backport/website

#12880 Bump github.com/go-jose/go-jose/v3 to address CVE-2024-28180
  go.mod
  go.sum
Labels: security

#12879 chore: remove repetitive words
  website/content/docs/templates/hcl_templates/functions/contextual/env.mdx
  website/content/guides/1.7-template-upgrade.mdx
  website/content/partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
Labels: tech-debt, backport/1.10.x

#12877 Update CHANGELOG
  CHANGELOG.md
Labels: tech-debt

#12886 command: support local paths for plugins remove
  command/plugins_remove.go
Labels: enhancement

#12889 test: remove directory
  test/README.md
  test/builder_googlecompute.bats
  test/builder_hyperone.bats
  test/builder_lxc.bats
  test/cli.bats
  test/communicator_ssh.bats
  test/fixtures/amazon-ebs/ami_region_copy.json
  test/fixtures/amazon-ebs/minimal.json
  test/fixtures/builder-googlecompute/minimal.json
  test/fixtures/builder-hyperone/chroot.json
  test/fixtures/builder-hyperone/minimal.json
  test/fixtures/builder-hyperone/new-syntax.pkr.hcl
  test/fixtures/builder-linode/minimal.json
  test/fixtures/builder-lxc/minimal.json
  test/fixtures/communicator-ssh/local-tunnel.json
  test/fixtures/communicator-ssh/remote-tunnel.json
  test/fixtures/provisioner-file/dir/file.txt
  test/fixtures/provisioner-file/dir_no_trailing.json
  test/fixtures/provisioner-file/dir_no_trailing_sftp.json
  test/fixtures/provisioner-file/dir_with_trailing.json
  test/fixtures/provisioner-file/dir_with_trailing_sftp.json
  test/fixtures/provisioner-file/file.json
  test/fixtures/provisioner-file/file.txt
  test/fixtures/provisioner-file/file_sftp.json
  test/fixtures/provisioner-shell/inline.json
  test/fixtures/provisioner-shell/script.json
  test/fixtures/provisioner-shell/script.sh
  test/fixtures/provisioner-shell/scripts.json
  test/provisioner_file.bats
  test/provisioner_shell.bats
  test/test_helper.bash
Labels: tech-debt

#12891 HPR-1537: Packer Core sends metadata to HCP Packer in UpdateBuild API
  go.mod
  go.sum
  internal/hcp/api/service_build.go
  internal/hcp/registry/hcl.go
  internal/hcp/registry/json.go
  internal/hcp/registry/types.bucket.go
  internal/hcp/registry/types.builds.go
Labels: hcp
