Repository hashicorp/packer, pull requests merged in 2024-12, with the labels that each got.

#13231 acctest: Gadgets for testing files
  packer_test/common/check/file_gadgets.go
Labels: enhancement

#13230 Test add compilation queue and customisations
  packer_test/common/plugin.go
  packer_test/common/suite.go
Labels: enhancement

#13233 go.mod: bump x/crypto to v0.31.0
  go.mod
  go.sum
Labels: security

#13235 command: copy AWS plugin structures for upgrade
  command/hcl2_upgrade.go
  go.mod
  go.sum
Labels: tech-debt

#13243 go.mod: bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: tech-debt, dependencies, security

#13244 docs: make TMPDIR clickable
  website/content/docs/configure.mdx
Labels: docs
